package demo

// The simulated screen.
//
// The interactive-control path ends in a browser decoding H.264 that a handset's
// encoder produced. There is no handset here, so the demo replays a clip that
// ffmpeg produced instead — a real, decodable, Annex-B elementary stream framed
// exactly as scrcpy frames one, looping forever with a timestamp that keeps
// advancing.
//
// WHAT THIS PROVES AND WHAT IT DOES NOT. It proves the transport: the framing,
// the two sockets, the session header, the splice through the api, the decode in
// the browser, and the coordinates a touch travels in. It proves NOTHING about a
// phone. The command line the server would be started with is built from the
// protocol and has never been accepted by a device; the jar below is not a jar;
// and the picture is a test pattern, not a screen. A run against real hardware
// should be read as a first run.
//
// The clip is committed in test/fakeadb/testdata and regenerated by
// scripts/make-screen-fixture.sh. It is 288x640 at 12 fps with an IDR every
// twelve frames, which is what makes a loop point that a decoder can join.

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/flaviopadilha/device-farmer/internal/artifacts"
	"github.com/flaviopadilha/device-farmer/test/fakeadb"
)

// The placeholder server jar.
//
// It is not a jar and the fake never opens it: what the demo needs is an
// artifact whose digest is pinnable, so that the whole ledger path —
// artifacts.EnsureOnDevice, the push, farm.device_artifacts, the skip on the
// second session — runs exactly as it would in production instead of being
// stubbed out. A real scrcpy-server.jar is Apache-2.0 and could be vendored;
// committing a binary this repository cannot build from source, to make a demo
// look more real than it is, is the trade this file declines.
//
// The bytes say so, in case somebody finds one on a device and wonders.
const ScreenServerJarBody = "device-farmer demo placeholder for scrcpy-server.jar\n" +
	"This is NOT a scrcpy server. The demo's fake ADB replays a recorded clip;\n" +
	"nothing on a device ever reads these bytes. See internal/demo/screen.go.\n"

// ScreenServerVersion is what the demo passes as the server's version argument.
// It is a real scrcpy version so that the command line the fence proxy admits is
// the shape a real one would be, not a placeholder that would need widening.
const ScreenServerVersion = "3.1"

// ScreenServerSHA is the digest of ScreenServerJarBody, written out rather than
// computed at startup so that docker-compose.yml and the Makefile can set
// FARM_SCREEN_SERVER_SHA to a literal an operator can read and compare.
//
// TestTheDemoJarDigestIsWhatTheDeploymentsPin fails if the two ever part.
const ScreenServerSHA = "c950e8bcb79fb19a05678ba321f8694700db6e6b6b67fbddfd9f8a90d2deca43"

// screenFPS is the fixture's frame rate, and it has to be the fixture's: the
// splitter timestamps each access unit from it, and a rate that disagreed with
// the clip would hand a decoder frames due faster or slower than they arrive.
const screenFPS = 12

// SeedScreenServer puts the placeholder jar in the artifact store.
//
// Idempotent by construction: artifacts are content-addressed, so a second run
// against a database that already has it is a no-op that returns the same row.
// The demo restarts often — every `docker compose up` — and a seed that failed
// the second time would make the screen work only on a fresh volume.
func SeedScreenServer(ctx context.Context, store *artifacts.Store) error {
	if store == nil {
		return nil
	}
	res, err := store.Put(ctx, strings.NewReader(ScreenServerJarBody),
		artifacts.KindFile, "scrcpy-server-demo-placeholder")
	if err != nil {
		return fmt.Errorf("demo: seed the screen server artifact: %w", err)
	}
	if res.Artifact.SHA256 != ScreenServerSHA {
		// Unreachable while the test below passes, and checked anyway: the
		// alternative is a demo that pushes bytes the api will not name, and
		// discovers it as a 404 from the artifact store on the first screen.
		return fmt.Errorf("demo: the screen server artifact stored as %s, and %s is pinned; "+
			"FARM_SCREEN_SERVER_SHA names a blob that is not there",
			res.Artifact.SHA256, ScreenServerSHA)
	}
	return nil
}

// screenSHA is the digest of the placeholder, computed. It exists for the test.
func screenSHA() string {
	sum := sha256.Sum256([]byte(ScreenServerJarBody))
	return hex.EncodeToString(sum[:])
}

// installScreenFixtures teaches one fake server to serve a live screen on every
// device it holds.
//
// Every device, rather than one: an operator clicking through the fleet grid
// should not have to discover which of fifty-six positions is the one that was
// wired. The cost is a slice header per device — the clip itself is shared,
// because ScrcpyPacketsFromAnnexB returns sub-slices of one embedded array.
func installScreenFixtures(srv *fakeadb.Server, devs []*simDevice, log *slog.Logger) {
	packets, err := fakeadb.ScrcpyPacketsFromAnnexB(fakeadb.ScreenFixture(), screenFPS)
	if err != nil {
		// Not fatal. A demo that refuses to start because one of its fixtures
		// could not be framed would take the whole simulated farm down over a
		// feature nobody has asked for yet; the screen routes will report
		// themselves unavailable, which is the accurate thing for them to say.
		log.Warn("the screen fixture could not be framed; devices in this demo will have no screen",
			"err", err,
			"consequence", "GET /api/v1/devices/{id}/screen answers 502 for every device")
		return
	}

	for _, d := range devs {
		srv.Apply(fakeadb.ScrcpyFixture(fakeadb.ScrcpyConfig{
			Devpath: d.devpath,
			// The geometry the clip was encoded at. It has to be the clip's:
			// this is the coordinate space every touch is expressed in, and a
			// session header that disagreed with the pictures behind it would
			// put every tap in the wrong place while looking entirely correct.
			Width:   288,
			Height:  640,
			Packets: packets,
			// One frame interval between packets, so the stream arrives at the
			// rate it was encoded at rather than as fast as a loopback socket
			// can be filled. A decoder handed four seconds of video in one
			// burst displays the last frame and looks frozen.
			PacketGap: time.Second / screenFPS,
			VideoLoop: true,
			ServerLog: fmt.Sprintf("[server] INFO: device-farmer demo, %s, replaying a "+
				"recorded clip. No handset is attached.\n", d.rackSlot),
		}))
	}
}
